export const keywords: string[] = [
  "Dùng",
  "Sử dụng",
  "Tác dụng",
  "Ảnh hưởng",
  "Hiệu quả",
  "Phản ứng phụ",
  "Tác dụng phụ",
  "Gây hại",
  "Gây",
  "Nguy hiểm",
  "Độc hại",
  "Cảnh báo",
  "Chú Ý",
  "Không nên dùng",
  "Chỉ định",
  "Liều lượng",
  "Thận trọng",
  "Tương tác thuốc",
];
