name: Node.js CI

on:
  push:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: 'yarn'
      - name: Install dependencies
        run: yarn install
      - name: Run tests
        run: yarn test

  build-and-deploy:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'merge')
    needs: test
    steps:
      - uses: actions/checkout@v2
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_REGISTRY_USER }}/${{ github.event.repository.name }}:latest
      - name: Deploy to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASS }}
          # key: ${{ secrets.KEY }}
          script: |
            docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_REGISTRY_USER }}/${{ github.event.repository.name }}) || true
            docker rm $(docker ps -aq --filter ancestor=${{ secrets.DOCKER_REGISTRY_USER }}/${{ github.event.repository.name }}) || true
            docker rmi $(docker images -q ${{ secrets.DOCKER_REGISTRY_USER }}/${{ github.event.repository.name }}) || true
            echo "${{ secrets.DOCKER_REGISTRY_PASS }}" | docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin
            docker run -d -p ${{ secrets.PORT }}:${{ secrets.PORT }} \
              -e PORT=${{ secrets.PORT }} \
              -e NODE_ENV=${{ secrets.NODE_ENV }} \
              -e BROWSER_WSE=${{ secrets.BROWSER_WSE }} \
              ${{ secrets.DOCKER_REGISTRY_USER }}/${{ github.event.repository.name }}
