name: Node.js CI

on:
  push:
    branches:
      - "*"
  pull_request:
    branches: [develop]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "yarn"
      - run: yarn install
      - run: yarn test
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_REGISTRY_USER }}
          password: ${{ secrets.DOCKER_REGISTRY_PASS }}
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ${{ github.event.repository.name }}:latest

  deploy:
    if: github.ref == 'refs/heads/develop' && (github.event_name == 'push' || github.event_name == 'merge')
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "${{ secrets.DOCKER_REGISTRY_PASS }}" | docker login --username ${{ secrets.DOCKER_REGISTRY_USER }} --password-stdin
            docker ps -q --filter ancestor=${{ github.event.repository.name }} | xargs -r docker stop | xargs -r docker rm -f || true
            docker images -q ${{ github.event.repository.name }} | xargs -r docker rmi -f || true
            docker run -d -p 8001:8001 --network=host -e CHAT_GPT_KEY=${{ secrets.CHAT_GPT_KEY }} -e GG_API_KEY=${{ secrets.GG_API_KEY }} -e GG_CX=${{ secrets.GG_CX }} ${{ github.event.repository.name }}
